weatherApp/weather/urls.py
from django.urls import path

from . import views

app_name = "weather"
urlpatterns = [
    path('', views.index, name='index'),
    path('comfortAsk/', views.comfortAsk, name='comfortAsk'),
    path('submission/', views.submission, name='submission'),
    # path('redirect/', views.after_vote_redirect, name="redirect")
    # ex: /polls/5/
    # path('<int:question_id>/', views.detail, name='detail'),
    # # ex: /polls/5/vote/
    # path('<int:question_id>/vote/', views.vote, name='vote'),
]

weatherApp/weatherApp/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    url(r'^weather/', include('weather.urls')),
    url(r'^admin/', admin.site.urls),
]

weatherApp/weather/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.utils import timezone

import datetime

# Create your models here.

class WeatherData(models.Model):
    temperature = models.IntegerField()
    apparent_temp = models.IntegerField()
    humidity = models.FloatField()
    precip_prob = models.FloatField()
    windSpeed = models.FloatField()
    cloudiness = models.CharField(max_length=30)
    time = models.DateTimeField()
    sunrise = models.DateTimeField()
    sunsetTime = models.DateTimeField()

class UserDataPoint(models.Model):
    feeling = models.IntegerField() #1-5
    recordedWeather = models.OneToOneField(WeatherData, on_delete=models.CASCADE)

weatherApp/weather/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import mimetypes
from . import apiCaller
from . import twelveHourForecast
from . import stats_analysis

from django.shortcuts import get_object_or_404, render

from django.http import HttpResponse, HttpResponseRedirect
from django.http import Http404
from django.urls import reverse

from .models import UserDataPoint, WeatherData

weather_moods = {
    "-1": None,
    "0": "freezing!",
    "1": "a little chilly.",
    "2": "just right.",
    "3": "a bit warm.",
    "4": "burnin' hot."
}

weather_pics = {
    "-1": None,
    "0": "weather/svgGraphics/Freezing.svg",
    "1": "weather/svgGraphics/Chilly.svg",
    "2": "weather/svgGraphics/JustRightlogo.svg",
    "3": "weather/svgGraphics/Toastylogo.svg",
    "4": "weather/svgGraphics/OnFirelogo.svg"
}

appropriate_clothing = {
    "-1": None,
    "0": ["weather/svgGraphics/clothing/jacket.svg", "weather/svgGraphics/clothing/jacket.svg"],
    "1": ["weather/svgGraphics/clothing/jacket.svg", "weather/svgGraphics/clothing/longsleeve.svg"],
    "2": ["weather/svgGraphics/clothing/tshirt.svg", "weather/svgGraphics/clothing/longsleeve.svg"],
    "3": ["weather/svgGraphics/clothing/tshirt.svg", "weather/svgGraphics/clothing/sunglasses.svg"],
    "4": ["weather/svgGraphics/clothing/tanktop.svg", "weather/svgGraphics/clothing/sunglasses.svg"]
}

time_of_day_pics = {
    "day": "weather/svgGraphics/Sun.svg",
    "night": "weather/svgGraphics/Moon.svg"
}

def index(request):
    currentWeather = apiCaller.get_current_dict()
    dailyWeather = apiCaller.get_daily_dict()
    current_temp = currentWeather['current_temperature']

    hourly_forecast = twelveHourForecast.run()
    unzip_hourly = list(zip(*hourly_forecast))
    hours = change_from_military_time(unzip_hourly[0])
    hourly_temps = unzip_hourly[1]

    feeling_prediction = str(stats_analysis.find_closest_feeling(current_temp))

    if currentWeather['current_time'] >= dailyWeather['sunrise_time'] and currentWeather['current_time'] < dailyWeather['sunset_time']:
        time_of_day = "day"
    else:
        time_of_day = "night"

    context = {
        'current_temperature': current_temp,
        'current_wind_speed': currentWeather['current_windSpeed'],
        'feeling_prediction': weather_moods[feeling_prediction],
        'feeling_prediction_pic': weather_pics[feeling_prediction],
        'suggested_clothing_1': appropriate_clothing[feeling_prediction][0],
        'suggested_clothing_2': appropriate_clothing[feeling_prediction][1],
        'user_voted': True if 'user_voted' in request.session else False,
        'selected_choice': "-1" if 'selected_choice' not in request.session else request.session['selected_choice'],
        'user_data_count': UserDataPoint.objects.count(),
        'hours': hours,
        'hourly_temps': hourly_temps,
        'blurb': generate_blurb(currentWeather, dailyWeather, feeling_prediction),
        'time_of_day': time_of_day_pics[time_of_day]
    }
    context['weather_mood'] = weather_moods[context['selected_choice']]
    context['weather_pic'] = weather_pics[context['selected_choice']]

    return render(request, 'weather/index.html', context)

# def after_vote_redirect(request):
#     currentWeather = apiCaller.get_current_dict()

#     context = {
#         'current_temperature': currentWeather['current_temperature'],
#         'current_wind_speed': currentWeather['current_windSpeed'],
#         'user_voted': True,

#     }

#     return render(request, 'weather/index.html', context)

def comfortAsk(request):
    return render(request, 'weather/comfortAsk.html')

def submission(request):
    request_copy = request.POST.copy()
    try:
        request_copy.pop("csrfmiddlewaretoken")
        selected_choice = request_copy.popitem()[0]
        selected_choice = selected_choice[0]
        request.session['selected_choice'] = selected_choice
        request.session['user_voted'] = True
    except (KeyError):
        # Redisplay the ask form.
        return render(request, 'weather/comfortAsk.html', {
            'error_message': str(request.POST),
        })

    currentWeather = apiCaller.get_current_dict()
    dailyWeather = apiCaller.get_daily_dict()
    currentWeatherData = WeatherData(
        temperature = currentWeather['current_temperature'],
        apparent_temp = currentWeather['current_apparentTemperature'],
        humidity = currentWeather['current_humidity'],
        precip_prob = currentWeather['current_precipProbability'],
        windSpeed = currentWeather['current_windSpeed'],
        cloudiness = currentWeather['current_summary'],
        time = currentWeather['current_time'],
        sunrise = "2019-02-15 05:30" if 'daily_sunriseTime' not in dailyWeather else dailyWeather['daily_sunriseTime'],
        sunsetTime = "2019-02-15 05:30" if "daily_sunsetTime" not in dailyWeather else dailyWeather['daily_sunsetTime']
        #sunrise = dailyWeather['daily_sunriseTime'],
        #sunsetTime = dailyWeather['daily_sunsetTime']
    )

    currentWeatherData.save()
    dataPoint = UserDataPoint()
    dataPoint.feeling = int(request.session['selected_choice'])
    dataPoint.recordedWeather = currentWeatherData
    dataPoint.save()

    return HttpResponseRedirect(reverse('weather:index'))


def generate_blurb(currentWeather: dict, dailyWeather: dict, feel: str):
    currentWeather = apiCaller.get_current_dict()
    feel = int(feel)

    blurb = ''
    # hour_min_sec = currentWeather['current_time'].split(' ')[1].split(':')
    # time_in_min = int(hour_min_sec[0])*60 + int(hour_min_sec[1]) #0-1440 minutes
    # if 240 <= time_in_min < 720:
    #     blurb += "Good Morning! "
    # elif 720 <=  time_in_min < 1020:
    #     blurb += "Good Afternoon! "
    # elif 1020 <= time_in_min < 1440:
    #     blurb += "Good Evening! "
    # else:
    #     blurb += "Good Day! "

    blurb += "It's going to be "

    if feel == 0:
        blurb += "very cold "
    elif feel == 1:
        blurb += "a little chilly "
    elif feel == 2:
        blurb += "just how you like it "
    elif feel == 3:
        blurb += "a bit warm "
    elif feel == 4:
        blurb += "very hot "
    else:
        blurb += "magical "

    blurb += "outside today."

    if (dailyWeather['daily_summary']):
        blurb += " It will be raining today, so bring an umbrella! "
    if (dailyWeather['daily_precipProbability']):
        blurb += " It will be sunny out today, so bring your shades!"

    if (dailyWeather['daily_apparentTemperatureHigh'] > 90 and dailyWeather['daily_humidity'] >= 0.98):
        blurb += " Feels like a lawless swampland out today, so bring your guns!"
    if (dailyWeather['daily_apparentTemperatureHigh'] > 90 and dailyWeather['daily_windSpeed'] >= 30):
        blurb += " Hot and windy! Be careful Icarus!"
    if (dailyWeather['daily_apparentTemperatureHigh'] == 69 and dailyWeather['daily_humidity'] == .69):
        blurb += " Hehe."

    return blurb

def change_from_military_time(hours: tuple):
    hours_list = []
    for each in hours:
        newTime = ""
        if int(each) > 12:
            newTime = str(each-12) + 'pm'
        elif int(each) == 12:
            newTime = str(each) + 'pm'
        elif int(each) == 0:
            newTime = '12am'
        else:
            newTime = str(each) + 'am'
        hours_list.append(newTime)

    return hours_list

weatherApp/weather/templates/weather/comfortAsk.html
<!doctype html>
<html>

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <!-- CSS Stylesheet -->
  {% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'weather/WeatherApp.css' %}">
  <title>WeatherApp</title>
</head>
<body>
  <div id="logo"><img src="{% static "weather/svgGraphics/logotransluscent.svg" %}"></div>
  <div id="selection" class="">
    <div class="something d-flex flex-row justify-content-center">
      <div class="heightAdjuster">
      <div id="question"><p>How do you feel today?</p></div>
      <form class="d-flex flex-row" action="{% url 'weather:submission' %}" choice="" method="post">
        {% csrf_token %}
              <div id="freezing">
              <input type="image" src="{% static "weather/svgGraphics/FreezinglogowithShadow.svg" %}" alt="My image" name="0">
              <p class="Description">Freezing</p>
              </div>
              <div id="chilly">
              <input type="image" src="{% static "weather/svgGraphics/ChillylogowithShadow.svg" %}" alt="My image" name="1">
              <p class="Description">Chilly</p>
              </div>
              <div id="justright">
              <input type="image" src="{% static "weather/svgGraphics/JustRightlogowithShadow.svg" %}" alt="My image" name="2">
              <p class="Description">Just Right</p>
              </div>
              <div id="toasty">
              <input type="image" src="{% static "weather/svgGraphics/ToastylogowithShadow.svg" %}" alt="My image" name="3">
              <p class="Description">Toasty</p>
              </div>
              <div id="onfire">
              <input type="image" src="{% static "weather/svgGraphics/OnFirelogowithShadow.svg" %}" alt="My image" name="4">
              <p class="Description">On Fire</p>
              </div>
              </div>
            </div>
          </form>
      </div>
    </div>
  </div>
  <!-- JavaScript: placed at the end of the document so the pages load faster -->
  		<!-- jQuery library -->
  		<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>

  		<!-- Popper -->
  		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>

  		<!-- Latest compiled and minified Bootstrap JavaScript -->
  		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

weatherApp/weather/templates/weather/index.html
<!doctype html>
<html>

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <!-- CSS Stylesheet -->
  {% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'weather/WeatherApp.css' %}">
  <title>WeatherApp</title>
</head>
<body>

  <!--
  <img src="{% static "weather/svgGraphics/Freezing.svg" %}" alt="My image">
  <img src="{% static "weather/svgGraphics/Chilly.svg" %}" alt="My image">
  <img src="{% static "weather/svgGraphics/JustRightlogo.svg" %}" alt="My image">
  <img src="{% static "weather/svgGraphics/Toastylogo.svg" %}" alt="My image">
  <img src="{% static "weather/svgGraphics/OnFirelogo.svg" %}" alt="My image">
  <img src="{% static "weather/svgGraphics/Sun.svg" %}" alt="My image">
  <img src="{% static "weather/svgGraphics/Moon.svg" %}" alt="My image">
  <img src="{% static "weather/svgGraphics/Cloud.svg" %}" alt="My image">
  <img src="{% static "weather/svgGraphics/CloudwithSnow.svg" %}" alt="My image">
  <img src="{% static "weather/svgGraphics/CloudwithRain.svg" %}" alt="My image">
-->

    <div class="row" id="rowOne">
      <div class="col-sm-3" id="column1">
        <div id="locationBox">
          <img src="{% static "weather/svgGraphics/LocationLogo.svg" %}" alt="My image">
          <span>Irvine, CA</spans>
        </div>
        <div id="statisticalValue">
          {% if user_voted == False %}
            <span>It's going to be</span>
            <!-- This button changes based on input-->
            <img src="{% static feeling_prediction_pic %}" alt="My image">
            <span>{{feeling_prediction}} <br>
          {% else%}
            <span>You said today was</span>
            <img src="{% static weather_pic %}" alt="My image">
            <span>{{weather_mood}}<br>
            <p>{{user_data_count}}</p>
          {% endif %}
          <div id="disclaimer"><a href="comfortAsk/"> Were we wrong?<br>Help us improve our predictions.</a></span></div>
        </div>
      </div>
      <div class="col-sm-2" id="columnTwo">
        <!-- Temperature value is based on API -->
        <div id="temperature"><span> {{current_temperature|stringformat:".0f"}}&#176;F </span></div>
        <!-- Weather type image is based on API -->
        <div id="weatherType"><img src="{% static time_of_day %}" alt="My image"></div>
        <!-- Wind speed value is based on API -->
        <div id="windSpeed"><span>{{current_wind_speed|stringformat:".0f"}} mph wind</span></div>
      </div>
      <div class="col-sm-7" id="columnThree">
        <div id="largeBox">
          <span> Suggested Layers</span> <img src="{% static suggested_clothing_1 %}" alt="My image"><img src="{% static suggested_clothing_2 %}" alt="My image">
          <p>{{blurb}}</p>
        </div>
      </div>
    </div>

    <div class="row" id="rowTwo">
      <div class="col-sm-12" id="columnThree">
        <div id="twelvehourForecast">
          <div class="scrollmenu">
            <div id="currentTimeplusOne"><span class='hourtime'>{{hours.0}}</span><br><span class='temp'>{{hourly_temps.0|stringformat:".0f"}}&#176;F</span></div>
            <div id="currentTimeplusTwo"><span class='hourtime'>{{hours.1}}</span><br><span class='temp'>{{hourly_temps.1|stringformat:".0f"}}&#176;F</span></div>
            <div id="currentTimeplusThree"><span class='hourtime'>{{hours.2}}</span><br><span class='temp'>{{hourly_temps.2|stringformat:".0f"}}&#176;F</span></div>
            <div id="currentTimeplusFour"><span class='hourtime'>{{hours.3}}</span><br><span class='temp'>{{hourly_temps.3|stringformat:".0f"}}&#176;F</span></div>
            <div id="currentTimeplusFive"><span class='hourtime'>{{hours.4}}</span><br><span class='temp'>{{hourly_temps.4|stringformat:".0f"}}&#176;F</span></div>
            <div id="currentTimeplusSix"><span class='hourtime'>{{hours.5}}</span><br><span class='temp'>{{hourly_temps.5|stringformat:".0f"}}&#176;F</span></div>
            <div id="currentTimeplusSeven"><span class='hourtime'>{{hours.6}}</span><br><span class='temp'>{{hourly_temps.6|stringformat:".0f"}}&#176;F</span></div>
            <div id="currentTimeplusEight"><span class='hourtime'>{{hours.7}}</span><br><span class='temp'>{{hourly_temps.7|stringformat:".0f"}}&#176;F</span></div>
            <div id="currentTimeplusNine"><span class='hourtime'>{{hours.8}}</span><br><span class='temp'>{{hourly_temps.8|stringformat:".0f"}}&#176;F</span></div>
            <div id="currentTimeplusTen"><span class='hourtime'>{{hours.9}}</span><br><span class='temp'>{{hourly_temps.9|stringformat:".0f"}}&#176;F</span></div>
            <div id="currentTimeplusEleven"><span class='hourtime'>{{hours.10}}</span><br><span class='temp'>{{hourly_temps.10|stringformat:".0f"}}&#176;F</span></div>
            <div id="currentTimeplusTwelve"><span class='hourtime'>{{hours.11}}</span><br><span class='temp'>{{hourly_temps.11|stringformat:".0f"}}&#176;F</span></div>
        </div>
        </div>
      </div>
    </div>



  <!-- JavaScript: placed at the end of the document so the pages load faster -->
  		<!-- jQuery library -->
  		<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>

  		<!-- Popper -->
  		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>

  		<!-- Latest compiled and minified Bootstrap JavaScript -->
  		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>

</html>